version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: stock_game_db
    environment:
      POSTGRES_DB: stock_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
